language: R
cache: packages
r:
  - oldrel
  - release
  - devel
r_github_packages:
  - r-lib/covr
install:
- R -e "install.packages('testthat')"
- R -e "install.packages('jsonlite')"
- R -e "install.packages('lintr')"
- R -e "install.packages('magrittr')"
script:
- R -e "source('bin/run_lints.R')"
after_success:
  - Rscript -e 'covr::coveralls()'
